// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7mcFG2m86UifJKj_ip8F19XfnViLGRfU',
    appId: '1:771978747538:web:7ec72b8cde204d80d0104b',
    messagingSenderId: '771978747538',
    projectId: 'projectt1-18284',
    authDomain: 'projectt1-18284.firebaseapp.com',
    storageBucket: 'projectt1-18284.firebasestorage.app',
    measurementId: 'G-2P1FD4GJV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd3zm01GJdv-K6pHw0jL4y8LHtIpeQZWU',
    appId: '1:771978747538:android:9d316cbb9ab4a551d0104b',
    messagingSenderId: '771978747538',
    projectId: 'projectt1-18284',
    storageBucket: 'projectt1-18284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG2Eq12PSBwwJmJGB9WeZxawoSKbCyI0Q',
    appId: '1:771978747538:ios:b9980c39d8f7c65cd0104b',
    messagingSenderId: '771978747538',
    projectId: 'projectt1-18284',
    storageBucket: 'projectt1-18284.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG2Eq12PSBwwJmJGB9WeZxawoSKbCyI0Q',
    appId: '1:771978747538:ios:b9980c39d8f7c65cd0104b',
    messagingSenderId: '771978747538',
    projectId: 'projectt1-18284',
    storageBucket: 'projectt1-18284.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7mcFG2m86UifJKj_ip8F19XfnViLGRfU',
    appId: '1:771978747538:web:81b376b5299fed90d0104b',
    messagingSenderId: '771978747538',
    projectId: 'projectt1-18284',
    authDomain: 'projectt1-18284.firebaseapp.com',
    storageBucket: 'projectt1-18284.firebasestorage.app',
    measurementId: 'G-XL82ELKHE7',
  );
}
